# Generated by Django 3.0.4 on 2020-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200405_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_subcatagory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
