# Generated by Django 3.0.4 on 2020-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_product_product_subcatagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacter_name', models.CharField(max_length=30)),
                ('contacter_mail', models.CharField(max_length=30)),
                ('contacter_phone', models.ImageField(upload_to='')),
                ('contacter_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
