# Generated by Django 3.0.4 on 2020-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='contacter_phone',
            field=models.IntegerField(default=0),
        ),
    ]
