# Generated by Django 3.0.4 on 2020-04-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20200409_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='contacter_phone',
            field=models.CharField(max_length=13),
        ),
    ]
