# Generated by Django 3.0.4 on 2020-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_orderupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdated',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
